apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
  - ../../base

images:
  - name: harbor.corp.vmbeans.com/bookstore/app
    newName: harbor.vcf.lab/bookstore/app
  - name: harbor.corp.vmbeans.com/library/postgres
    newName: harbor.vcf.lab/library/postgres
  - name: harbor.corp.vmbeans.com/library/redis
    newName: harbor.vcf.lab/library/redis
  - name: harbor.corp.vmbeans.com/library/elasticsearch
    newName: harbor.vcf.lab/library/elasticsearch
  - name: harbor.corp.vmbeans.com/library/minio/minio
    newName: harbor.vcf.lab/library/minio/minio

patches:
  - path: configmap-patch.yaml
  - path: httproute-patch.yaml
  - path: tls-patch.yaml
  - path: postgres-patch.yaml
  - path: elasticsearch-patch.yaml
  - path: redis-pvc-patch.yaml
  - path: minio-pvc-patch.yaml
