apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
  - ../../base

components:
  - ../../components/init-db

images:
  - name: harbor-01a.vcf.lab/bookstore/app
    newName: harbor-01a.vcf.lab/bookstore/app
    newTag: latest
  - name: harbor-01a.vcf.lab/library/postgres
    newName: harbor-01a.vcf.lab/library/postgres
  - name: harbor-01a.vcf.lab/library/redis
    newName: harbor-01a.vcf.lab/library/redis
  - name: harbor-01a.vcf.lab/library/elasticsearch
    newName: harbor-01a.vcf.lab/library/elasticsearch
  - name: harbor-01a.vcf.lab/library/minio/minio
    newName: harbor-01a.vcf.lab/library/minio/minio

secretGenerator:
  - name: app-secrets
    literals:
      - DB_USER=bookstore
      - DB_PASSWORD=bookstore-secret-pw
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin-secret
  - name: harbor-registry-secret
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"harbor-01a.vcf.lab":{"username":"admin","password":"Harbor123!","auth":"YWRtaW46SGFyYm9yMTIzIQ=="}}}

patches:
  - path: configmap-patch.yaml
  - path: namespace-patch.yaml
  - path: httproute-patch.yaml
  - path: tls-patch.yaml
  - path: postgres-patch.yaml
  - path: redis-pvc-patch.yaml
  - path: minio-pvc-patch.yaml
  - path: init-db-job-patch.yaml
  # LAB DEMO STEP: To ENABLE Elasticsearch, comment out the two patches below,
  # AND uncomment the '- path: elasticsearch-patch.yaml' line below them.
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: elasticsearch
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: elasticsearch-service
        
  # - path: elasticsearch-patch.yaml
