apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        storageClassName: vsan-default-storage-policy
